DATA:
    ROOT: 'E:/DATASETS/TBAD-8/tbad-8/'
#    ROOT: '/root/autodl-fs/tbad-8/'
    TRAIN_FILE: 'datasets_splits/TBAD-8/train.txt'
    TEST_FILE: 'datasets_splits/TBAD-8/test.txt'
    DATASET: TBAD-8
    NUM_FRAMES: 16
    NUM_CLASSES: 8
    LABEL_LIST: 'labels/TBAD-8_labels.csv'
    IF_TEACHER: 1
    SHOTS: 8
    CACHE_SIZE: 8
MODEL:
    ARCH: ViT-L/14@336px
    YOLO: 'Yolo-model/yolov8n.pt'
    LOAD_ATTENTION: 0
TRAIN:
    LABEL_SMOOTH: 1
    IF_TEST: 0
    ZS: 1
    BATCH_SIZE: 1 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 20
    LR: 0.001
TIP_ADAPTER:
    CACHE_DIR: ''
    LOAD_CACHE: 0
    AUGMENT_EPOCH: 30
    LOAD_PRE_FEAT: 0
    INIT_BETA: 1
    INIT_ALPHA: 3
#OUTPUT: '/root/autodl-fs/results.csv'
OUTPUT: 'output_test_tip.csv'
SEARCH_HP: 1
SEARCH_SCALE: [7, 3]
SEARCH_STEP: [200, 20]
PREFIX: "The action of the person in the picture is"
SUFFIX: ''
TEMPORAL_POOLING: 'attention'