DATA:
#    ROOT: 'E:/DATASETS/TBAD-8/tbad-8/'
    ROOT: '/root/autodl-fs/ucf-101/'
    TRAIN_FILE: 'datasets_splits/UCF-101/train.txt'
    TEST_FILE: ''
    DATASET: UCF-101
    NUM_FRAMES: 16
    NUM_CLASSES: 8
    LABEL_LIST: 'labels/UCF-101_base_labels.csv'
    IF_TEACHER: 1
    SHOTS: 8
    CACHE_SIZE: 8
MODEL:
    ARCH: ViT-L/14@336px
    YOLO: 'Yolo-model/yolov8n.pt'
    LOAD_ATTENTION: 1
TRAIN:
    IF_TEST: 0
    ZS: 0
    BATCH_SIZE: 1 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 20
    LR: 0.001
TIP_ADAPTER:
    CACHE_DIR: ''
    LOAD_CACHE: 1
    AUGMENT_EPOCH: 30
    LOAD_PRE_FEAT: 1
    INIT_BETA: 1
    INIT_ALPHA: 3
OUTPUT: '/root/autodl-fs/results.csv'
#OUTPUT: 'output_test_tip.csv'
SEARCH_HP: 1
SEARCH_SCALE: [7, 3]
SEARCH_STEP: [200, 20]
PREFIX: ["The action of the person in the picture is", "A person was", "A photo of"]
SUFFIX: ''
TEMPORAL_POOLING: 'attention'
