DATA:
#    ROOT: 'E:/DATASETS/ucf10/ucf10/'
    ROOT: '/root/autodl-fs/ucf101/'
    TRAIN_FILE: 'datasets_splits/UCF-101/base_train.txt'
    VAL_FILE: 'datasets_splits/UCF-101/base_val.txt'
    DATASET: UCF-101
    NUM_FRAMES: 8
    NUM_CLASSES: 102
    INPUT_SIZE: 224
    LABEL_LIST: 'labels/UCF-101_base_labels.csv'
    IF_TEACHER: False
    INSTRUCTION_FT: True
MODEL:
    ARCH: ViT-B/32
    YOLO: 'Yolo-model/yolov8n.pt'
TRAIN:
    IF_PRETRAINED: True
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-04
#TRAINER:
#  TBA_CLIP:
#    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
#    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
#SAVE_FREQ: 30
