DATA:
#    ROOT: 'E:/DATASETS/hmdb51_org/videos/'
    ROOT: '/root/autodl-fs/videos/'
    TRAIN_FILE: 'datasets_splits/hmdb51/train.txt'
    TEST_FILE: 'datasets_splits/hmdb51/test/test.txt'
    DATASET: hmdb51
    NUM_FRAMES: 16
    NUM_CLASSES: 51
    LABEL_LIST: 'labels/hmdb51_org_base_labels_insFT.csv'
    IF_TEACHER: 0
    SHOTS: 2
    CACHE_SIZE: 2
MODEL:
    ARCH: ViT-L/14
    YOLO: 'Yolo-model/yolov8n.pt'
TRAIN:
    IF_TEST: 0
    ZS: 1
    BATCH_SIZE: 1 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 1
    LR: 0.001
TIP_ADAPTER:
    CACHE_DIR: ''
    LOAD_CACHE: 0
    AUGMENT_EPOCH: 1
    LOAD_PRE_FEAT: 0
    INIT_BETA: 1
    INIT_ALPHA: 3
OUTPUT: 'few_shot.csv'
SEARCH_HP: 1
SEARCH_SCALE: [7, 3]
SEARCH_STEP: [200, 20]
PREFIX: 'The action of the person in the picture is '
SUFFIX: ''
TEMPORAL_POOLING: 'mean'
