DATA:
    ROOT: '/root/autodl-fs/hmdb51/'
    TRAIN_FILE: 'datasets_splits/hmdb51/train.txt'
    TEST_FILE: 'datasets_splits/hmdb51/test_split_1.txt'
    DATASET: hmdb51
    NUM_FRAMES: 8
    NUM_CLASSES: 51
    LABEL_LIST: 'labels/hmdb51_org_base_labels_insFT.csv'
    IF_TEACHER: 1
    SHOTS: 8
    CACHE_SIZE: 8
MODEL:
    ARCH: ViT-L/14@336px
    YOLO: 'Yolo-model/yolov8n.pt'
    LOAD_ATTENTION: 1
    LOAD_LP: 1
    LOAD_ADAPTER: 1
TRAIN:
    LABEL_SMOOTH: 1
    ZS: 0
    LP: 1
    BATCH_SIZE: 8 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 15
    LR: 0.001
TIP_ADAPTER:
    CACHE_DIR: ''
    LOAD_CACHE: 1
    AUGMENT_EPOCH: 30
    LOAD_PRE_FEAT: 1
    INIT_BETA: 1
    INIT_ALPHA: 3
TEXT_PROMPT:
    N_CTX_PRE: 8
    CTX_PRE_INIT: "x x x x x x x x"
    N_CTX_POST: 3
    CTX_POST_INIT: "x x x"
    ONLY_LABEL: 0
OUTPUT: 'output_test_tip.csv'
SEARCH_HP: 1
SEARCH_SCALE: [7, 3]
SEARCH_STEP: [200, 20]
TEMPORAL_POOLING: 'attention'